### ISSUE TITLE
Messed up chat line

### ISSUE THREAD

**Issue by LinearXV** [DiscordStyles/Slate#10]
![image](https://user-images.githubusercontent.com/65974810/95687921-6f5ba900-0bbb-11eb-8772-a772ecf24e15.png)
I get this when go into DMs, I think it might be caused by [CharCounter - mwittrien](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/CharCounter). It is this for sure, because I enabled every plugin except this and it worked well.

**Comment by Gibbu** [comment]
Fixed
