### ISSUE TITLE
Invisible sticker and gif icons

### ISSUE THREAD

**Issue by Xanthus58** [DiscordStyles/Slate#102]
### Describe the bug
The sticker and icons in the chat bubble are missing/void

### To Reproduce  
> Install powercord
> Install Slate
> Join/connect to a server/dm
> Observe the bug

### Screenshots
![image](https://user-images.githubusercontent.com/66909997/175282601-2dd89917-5773-4988-831a-dc81977d7f68.png)

### Information (please complete the following information)
**Discord channel**: *Canary*  
**OS**: *Windows*  
**Mod**: *Powercord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Fixed
