### ISSUE TITLE
no highlighting on reactions that you have reacted to

### ISSUE THREAD

**Issue by winneratwin** [DiscordStyles/Slate#118]
### Describe the bug
the class for reactions that you have reacted to has changed to reactionMe-1PwQAc from reactionMe-3I9gFK which is in _reactions.scss

### To Reproduce  
react to a message and notice the number changing but the color isn't

### Information (please complete the following information)
**Discord channel**: Canary
**OS**: Linux
**Mod**: Powercord
**Discord language**: English, US

**Comment by Gibbu** [comment]
Fixed
