### ISSUE TITLE
Slate download button is not working

### ISSUE THREAD

**Issue by BlueStarBRS** [DiscordStyles/Slate#122]
this appers when you want to Download it
https://betterdiscord.net/ghdl?id=3358 movesyou to --> http://ww12.betterdiscord.net/
![image](https://user-images.githubusercontent.com/25110093/199136135-04008d41-cf0f-41b0-b801-58111ef852e8.png)

so Download not possible 

btw 
https://bdeditor.dev/

is sooo sick i love it great work

**Comment by Gibbu** [comment]
Because you're using the wrong website. https://betterdiscord.app/theme/Slate

**Comment by BlueStarBRS** [comment]
> Because you're using the wrong website. https://betterdiscord.app/theme/Slate

i use that what you linked on your github ^^ and the webiste for the plugin himself don´t link it correctly that i can download it from bd i know but i just informed you about the website for the theme himself 😅

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/200100466-6ee12731-cf56-4abf-a94c-0212f2d46ef0.png)
i eman this one

**Comment by Gibbu** [comment]
I totally forgot about that website.
