### ISSUE TITLE
[BUG] Slate user Panel bug

### ISSUE THREAD

**Issue by BlueStarBRS** [DiscordStyles/Slate#123]
### Describe the bug

_the background shadow from user panel is buged
![image](https://user-images.githubusercontent.com/25110093/200703517-f839662e-bb49-4e90-90a8-9293c8bbfe40.png)

version;
![image](https://user-images.githubusercontent.com/25110093/200703551-36b0d966-2a53-40a7-9e07-1114bf80ab88.png)

**Comment by Gibbu** [comment]
The user popout is fixed, but the user modal isn't. I'll fix that another time.
