### ISSUE TITLE
Messed-up compact mode look

### ISSUE THREAD

**Issue by Kan18** [DiscordStyles/Slate#15]
Messages in compact mode do not look great.
Previously, they looked like this:
![image](https://user-images.githubusercontent.com/24967425/97789850-431fc080-1b9a-11eb-99d8-bfdcb85df68b.png)
Now, they look like this (this screenshot has some empty space in it, which is unintentional):
<img width="616" alt="Screen Shot 2020-10-31 at 4 55 36 PM" src="https://user-images.githubusercontent.com/24967425/97789852-49ae3800-1b9a-11eb-89d0-0d8dd48f3794.png">
Could they please be fixed to be on one line?
Thanks for looking at this issue.

**Comment by piotr25691** [comment]
If you want to fix it by yourself, you can reverse the changes made in this commit:
https://github.com/DiscordStyles/Slate/commit/70fa03ca97b8c7df776a758ca9a72cb4f75941dd
and then it will look correct.
![obraz](https://user-images.githubusercontent.com/71488561/97810474-6454df80-1c74-11eb-9f51-c20e3a5c64cf.png)

**Comment by fluffapparition** [comment]
@piotr25691, could you point out one line in that commit that you think did most of the damage?

**Comment by Gibbu** [comment]
Fixed
