### ISSUE TITLE
@everyone confirmation prompt shows up incorrectly

### ISSUE THREAD

**Issue by piotr25691** [DiscordStyles/Slate#18]
The @everyone confirmation prompt shows up off-screen:
![obraz](https://user-images.githubusercontent.com/71488561/97845061-5cd11d00-1cec-11eb-866d-2899e9f3ba7c.png)
Then it moves itself but causes a large dislocation.
![obraz](https://user-images.githubusercontent.com/71488561/97845199-9570f680-1cec-11eb-994d-1ba321d69405.png)
![obraz](https://user-images.githubusercontent.com/71488561/97845222-9c980480-1cec-11eb-8ca1-f8fd07a34617.png)
Also, the prompt is not styled by the theme (at least not completely)

**Comment by Gibbu** [comment]
Don't `@everyone` then 
![image](https://user-images.githubusercontent.com/20338746/97861719-4eb8e600-1d58-11eb-999f-6a7dae99f1e4.png)

**Comment by piotr25691** [comment]
well do you know how to hide it then completely

**Comment by Gibbu** [comment]
Fixed.
