### ISSUE TITLE
small inputs, missing cursor pointer on nav items/buttons, font sizes

### ISSUE THREAD

**Issue by Venipa** [DiscordStyles/Slate#20]
im really liking this theme so far but there are several inputs that are to small in height and several buttons (and nav items) dont have a pointer cursor.

![image](https://user-images.githubusercontent.com/17952364/98713030-5c3d2400-2387-11eb-8387-5b270682023b.png)
should be
![image](https://user-images.githubusercontent.com/17952364/98713069-6c550380-2387-11eb-9785-d602a2c035fe.png)
edit (cursor): `--cursor: pointer;` fixes the pointer issue
edit (input size):
```
:root {
    --spacing: 12px;
    --input-height: 32px;
    --avatar-size-sm: 28px;
}
```
enlarges the buttons and inputs a bit

also there are some sections that needs some margins and font adjustments
![image](https://user-images.githubusercontent.com/17952364/98712963-46c7fa00-2387-11eb-9ba3-5177eebbc791.png)
![image](https://user-images.githubusercontent.com/17952364/98713007-53e4e900-2387-11eb-8000-91051237b43c.png)

**Comment by Gibbu** [comment]
Apart from the last 2 screenshots; cursor and input size all follow the GitHub Desktop design language. Meaning they're intentional.
We added those variables so people who didn't like them can change them.
