### ISSUE TITLE
Menu item alignment issues

### ISSUE THREAD

**Issue by Jwboucher94** [DiscordStyles/Slate#25]
![image](https://user-images.githubusercontent.com/2507616/101805843-8400e280-3b13-11eb-87d0-f4d9c6e8f324.png)
Several menus have issues such as this - This is the invite link page on channel settings

**Comment by Gibbu** [comment]
You must have an older version of Slate. Please update.

**Comment by Jwboucher94** [comment]
I just downloaded it a couple days ago, there's no new version

**Comment by Gibbu** [comment]
Oh I see why. That's in the channel settings and not server settings.

**Comment by Gibbu** [comment]
Fixed.
