### ISSUE TITLE
Stickers don't work.

### ISSUE THREAD

**Issue by ghost** [DiscordStyles/Slate#27]
https://media.discordapp.net/attachments/753838523626291303/792210011039989810/unknown.png

**Comment by Gibbu** [comment]
I don't currently have stickers so you'll have to deal with it for now.

**Comment by yeenohT** [comment]
You can try using a Discord Experiments plugin to enable them.

**Comment by DarviL82** [comment]
They are now available for everyone! 🙂

**Comment by Gibbu** [comment]
*Finally* fixed. Only took Discord 6+ months to make this available for everyone.
