### ISSUE TITLE
No LGBT palette

### ISSUE THREAD

**Issue by dperolio** [DiscordStyles/Slate#28]
I think it's an oversight by the developers (hopefully) that they haven't made an LGBT palette for Slate yet. Maybe have the palette animate through all the colors, or just use rainbow as the primary "color" throughout. I hope you will consider this matter.

**Comment by WinstonSepruko** [comment]
I definitely agree. This is a huge mistake, I don't want to have to result to flaming the developers of this theme on Twitter.

**Comment by Gibbu** [comment]
![477825238172958730](https://user-images.githubusercontent.com/20338746/103610284-e19e1880-4f73-11eb-826e-9b3dfd61af86.png)
