### ISSUE TITLE
UI is tiny at high resolution

### ISSUE THREAD

**Issue by alterae** [DiscordStyles/Slate#29]
On a 4k monitor, a lot of the UI appears very small, including both sidebars and all messages.  The chat font scale option in discord settings does not scale the font, so there's no way to fix this as a user.

**Comment by Gibbu** [comment]
Just increase Discord zoom level?

**Comment by Alterae** [comment]
Increasing Discord's zoom level makes the chat bigger, but at the cost of making the UI elements that are already reasonably sized (like the settings page and the sidebar width) too large.

**Comment by snessim** [comment]
Manually alter some of the hidden variables in the wiki then?

**Comment by Gibbu** [comment]
I finally was bothered to mess around with the chat and added 4 new variables.
```
--chat-font-size-xsm: var(--font-size-xsm);
--chat-font-size-sm: var(--font-size-sm);
--chat-font-size: var(--font-size);
--chat-avatar-size: var(--avatar-size);
```
The value is just the default be you can set them to be whatever.
