### ISSUE TITLE
Broken part of theme

### ISSUE THREAD

**Issue by Lorekin** [DiscordStyles/Slate#31]
Left click on Avatar
![Discord_rnaZxj7qAT](https://user-images.githubusercontent.com/26692817/105612019-1dd1d580-5dca-11eb-9c5c-28dae52613a1.png)
![Discord_vHyWKzSJJ1](https://user-images.githubusercontent.com/26692817/105612022-20342f80-5dca-11eb-848b-b3a20eb09db4.png)

**Comment by Gibbu** [comment]
This is an issue with how Discord calculated where to place the popout. Because we reduced the height Discord freaks out. Nothing we can do to fix this without breaking other popouts.
