### ISSUE TITLE
Theme breaks with Horiz Serverlist

### ISSUE THREAD

**Issue by ItsElectra** [DiscordStyles/Slate#32]
A part of the interface is cut off when Horizontal Server List is applied. The reason I find this a problem is because Gibbu works on this, and made the Horizontal Server List Mini-Theme. Please make the theme either adjust for this, or create a separate version for it, or something of the sort, thank you.

**Comment by Gibbu** [comment]
Open your `Slate.theme.css` file and remove the following:
![image](https://user-images.githubusercontent.com/20338746/105617853-dda83c80-5e35-11eb-9a12-2cb3aef4af43.png)
