### ISSUE TITLE
Online icon doesn't reflect if online on mobile or not

### ISSUE THREAD

**Issue by NuclearMeltdown** [DiscordStyles/Slate#33]
The status icons are always the same circular shape instead of distinctive shapes, just colored differently according to the online status. This is the case everywhere in the UI. The only place where the actual online status, including shape and mobile indicator, is shown, is in the DM header.

There have been instances where the mobile icon does show up in the UI, but that seems to be a bug instead of intentional behavior, as it only shows up if the online status of someone changes while viewing the list they are contained in, or if the said person's online status is loaded after the theme is, for example when scrolling the list.

**Comment by Gibbu** [comment]
Discord's statuses are very *very* limiting and are a huge pain to deal with. And the mobile indicators are are bug that we cannot fix as Discord doesn't update the element that we rely on.

**Comment by NuclearMeltdown** [comment]
Would there be a workaround for me to revert to Discord's default status icons or would that involve changing underlying code that breaks other things like positioning etc.? I pretty much rely on Discord showing me at a glance on my DM list, if someone is online on their PC or their phone. It isn't a huge deal if it doesn't work but it would be nice to have the option.
