### ISSUE TITLE
Conflict with Hide Servers / Channels Plugin

### ISSUE THREAD

**Issue by skyler544** [DiscordStyles/Slate#34]
First of all, thanks for your hard work. This theme looks great! 

As the title suggests, this isn't a bug with the theme per se, but I hope you could point me in the right direction to solve the conflict with [this](https://github.com/Arashiryuu/crap/blob/master/ToastIntegrated/HideServersChannelsRedux/HideServersChannelsRedux.plugin.js) plugin. 

The plugin provides buttons in the UI and keybindings to collapse the channel list / server list. Both buttons appear correctly with and without Slate, and the button/keybinding to hide the servers works with and without Slate as expected. However, the button/keybinding to hide the channel list causes the channel list to briefly collapse and then reopen (the plugin *does* work without Slate).

I've looked at the code for both Slate and the plugin in question, but my CSS/JS-Fu is essentially nonexistent and I wasn't able to make them play nice together. I decided to open this issue in the hope that you could fix the conflict or at least help me figure out how to fix it myself. 

Thanks!

**Comment by Gibbu** [comment]
Fixed.
