### ISSUE TITLE
Connections Logos gone

### ISSUE THREAD

**Issue by inbroso** [DiscordStyles/Slate#37]
Since I installed slate the connections logos of everyone are gone.
It looks like on the screenshot below.
![Untitled](https://user-images.githubusercontent.com/37818605/108760668-3c082e00-754e-11eb-8e11-3b7da8c3b4cc.png)

**Comment by Gibbu** [comment]
Can you provide more information?
Such as:
- Discord built
- Client Mod
- Operating System
- Slate version

**Comment by inbroso** [comment]
![tvpxEJSg](https://user-images.githubusercontent.com/37818605/108834243-3baf7780-75ce-11eb-8270-774fc8ee7840.png)
I hope that is enough?

**Comment by PoorPocketsMcNewHold** [comment]
Happening on powercord too. 
![image](https://user-images.githubusercontent.com/13170204/114720258-2afec080-9d38-11eb-9ef3-b174840c6395.png)

**Comment by Gibbu** [comment]
Is this still an issue?

**Comment by PoorPocketsMcNewHold** [comment]
It still does. 
![jWPQYPUjfE](https://user-images.githubusercontent.com/13170204/117248824-71a28080-adf5-11eb-9f8b-c64f2b5e355c.gif)

**Comment by Gibbu** [comment]
Ahhh, I found the issue. Re-enable your theme and check now?

**Comment by PoorPocketsMcNewHold** [comment]
Yep. Can confirm it has been solved.

**Comment by Gibbu** [comment]
Nice nice.
