### ISSUE TITLE
RadialStatus issues

### ISSUE THREAD

**Issue by sitiom** [DiscordStyles/Slate#39]
**Describe the bug**
RadialStatus outlines are off on the avatar icon on the bottom panel
And the hover icon becomes bigger.

**To Reproduce**
Have Slate theme with [RadialStatus](https://github.com/DiscordStyles/RadialStatus)

**Screenshots**
![image](https://user-images.githubusercontent.com/56180050/110790323-e0f36c80-82ab-11eb-95d5-11beb72e30e4.png)
![image](https://user-images.githubusercontent.com/56180050/110790868-83abeb00-82ac-11eb-8d4e-2c81d76f7cf3.png)

**Desktop (please complete the following information):**
Discord channel: Stable
OS: Windows
Mod: BetterDiscord

**Comment by Gibbu** [comment]
Hm... not much I can do about this without breaking it normally.

**Comment by sitiom** [comment]
wontfix?

**Comment by Gibbu** [comment]
Yes. As I said: I can't do much without breaking it normally.
