### ISSUE TITLE
Many icons missing

### ISSUE THREAD

**Issue by ItsElectra** [DiscordStyles/Slate#40]
All of the icons that are slate-specific are gone. This includes:
- The BBD settings icons (The discord settings icons are all just gears
- The connection button icon
- The home button icon
- The discord logo icon
- The attachment icon
- The gif, sticker and emoji icons

**Comment by Gibbu** [comment]
This should be fixed.

**Comment by LordMerc** [comment]
User icons take forever to load..

**Comment by Gibbu** [comment]
Please. Provide. Screenshots.

**Comment by ItsElectra** [comment]
![image](https://user-images.githubusercontent.com/59057998/114928480-a461e600-9e00-11eb-905f-9db595fec801.png)
oop the settings icons are missing and rearranged now (the rest is fixed)

**Comment by Gibbu** [comment]
Fixed.
