### ISSUE TITLE
"Upload to #channel" window not themed, cropped text

### ISSUE THREAD

**Issue by kamild1996** [DiscordStyles/Slate#44]
**Describe the bug**
"Upload to #channel" window not themed, cropped text

**To Reproduce**
Drag and drop a file onto the Discord window

**Screenshots**
![2021-04-05_12-39-22](https://user-images.githubusercontent.com/5320414/113565921-14f05200-960c-11eb-9bda-b3d528faef69.png)

**Desktop:**
Discord channel: Stable
OS: Windows
Mod: BetterDiscord

**Additional context**
*n/a*

**Comment by Gibbu** [comment]
Fixed.
