### ISSUE TITLE
Public servers button too low

### ISSUE THREAD

**Issue by abhatthal** [DiscordStyles/Slate#45]
The public servers button is cut off into the divider line. (See screenshots)

**Screenshots**
![image](https://user-images.githubusercontent.com/41220185/115741504-b08bfd00-a344-11eb-9ae3-3443b34464d6.png)
![image](https://user-images.githubusercontent.com/41220185/115742055-2a23eb00-a345-11eb-95dd-be471bb2134e.png)

**Desktop**
Discord channel: Stable
OS: OSX
Mod: BetterDiscord

**Additional context**
I resolved this issue by adding: `--toolbar-height: 30px;`

**Comment by Gibbu** [comment]
Fixed.
