### ISSUE TITLE
Full screen leaves a weird bar

### ISSUE THREAD

**Issue by mxd-Blum** [DiscordStyles/Slate#49]
**Describe the bug**  
When going into full screen view in a voice channel, there's a bar on the left that stays and takes up a considerable amount of the screen.   

**To Reproduce**  
Go into full screen in a voice channel

**Screenshots**  
![image](https://user-images.githubusercontent.com/83988461/117732834-c8b9a400-b1ad-11eb-9d37-6d854d4f4c7f.png)
![image](https://user-images.githubusercontent.com/83988461/117732854-d1aa7580-b1ad-11eb-978d-c96499cbbf2a.png)

**Infomation (please complete the following information):**  
Discord channel: Stable 
OS: Windows  
Mod: BetterDiscord
Discord language: English  

**Additional context**  
My first thought is that it might be an issue with one of my plugins, but this doesn't happen with any other theme.

**Comment by Gibbu** [comment]
Fixed.
