### ISSUE TITLE
Embeds are too wide

### ISSUE THREAD

**Issue by Diyamund** [DiscordStyles/Slate#50]
**Describe the bug**  
Embeds are very wide for some reason

**To Reproduce**  
Post an image. (more noticeable as a spoiler)

**Screenshots**  
![image](https://user-images.githubusercontent.com/44238627/118884312-e5e02800-b8bb-11eb-90a4-5c3a1af168a7.png)

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows 8.1 64-bit
Mod: BetterDiscord
Discord language: English (US)

**Comment by Gibbu** [comment]
Fixed.
