### ISSUE TITLE
All button styles are the same color

### ISSUE THREAD

**Issue by OrigamiToast** [DiscordStyles/Slate#51]
**Describe the bug**  
All button styles are the same color

**To Reproduce**  
Send a button component with any style other than one

**Screenshots**  
![](https://cdn.origamitoast.ga/2AI1WAYr.png)
![](https://cdn.origamitoast.ga/kihV7JXy.png)

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Win10
Mod: BetterDiscord
Discord language: English

**Additional context**  
See https://discord.com/developers/docs/interactions/message-components#buttons-button-styles

**Comment by Gibbu** [comment]
Newest update should fix this.
