### ISSUE TITLE
Inbox server icons too big and cut-off

### ISSUE THREAD

**Issue by piotr25691** [DiscordStyles/Slate#52]
**Describe the bug**  
The server icons in the inbox are too big and cut off

**To Reproduce**  
Usually this happens with just Slate.

**Screenshots**  
![image](https://user-images.githubusercontent.com/71488561/120994976-48269d00-c785-11eb-926d-33beab644ecc.png)
![image](https://user-images.githubusercontent.com/71488561/120995013-4f4dab00-c785-11eb-9898-67c5eea12df5.png)

**Infomation**  
Discord channel: *PTB*  
OS: *Windows*  
Mod: *BetterDiscord*  
Discord language: *English (US)*

**Additional context**  
I don't think these icons should that big.

**Comment by Gibbu** [comment]
Fixed.
