### ISSUE TITLE
Titlebar colour cannot be modified? 

### ISSUE THREAD

**Issue by dreadbalaur** [DiscordStyles/Slate#53]
The title bar cannot be affected by any "background-___" variables, at least for the ones currently listed on the wiki. Based on the original theme I was hoping that it would automatically match with the server bar colour.  

Discord channel: Stable  
OS: Windows 10  20H2 
Mod: BetterDiscord  
Discord language: English

**Comment by Gibbu** [comment]
The titlebar shares variables with the toolbar.
`--toolbar-background-alt` will change the background of the titlebar and the searchbar.

**Comment by dreadbalaur** [comment]
Oh, I think I mixed it up with the --toolbar-background-hover, hence why it didn't work. Thanks!
