### ISSUE TITLE
Nitro won't show up on slate

### ISSUE THREAD

**Issue by UrkiMimi** [DiscordStyles/Slate#55]
**Describe the bug**  
Friends button does not display properly

**To Reproduce**  
Go to Discord Home

**Screenshots**  
https://media.discordapp.net/attachments/840779388798107688/868968544426131456/unknown.png

**Infomation (please complete the following information):**  
Discord channel: *Canary*  
OS: *Windows*  
Mod: *Powercord*  
Discord language: *English*  

**Additional context**  
None

**Comment by Gibbu** [comment]
That is because you don't have this option enabled in Advanced Settings
![image](https://user-images.githubusercontent.com/20338746/128509281-e0bc3fa1-8522-4e9b-ad80-5d55be337bef.png)

I'll try fix it soon.
