### ISSUE TITLE
Base.ccs doesn't show up

### ISSUE THREAD

**Issue by Jan-aka-q0** [DiscordStyles/Slate#56]
The theme itself doesn't load on discord (AdjustableServerWidth does but that's a different repo), and when going to the base.css URL the file doesn't seem to be present

[Screenshot](https://jan.has-no-bra.in/55pZOAbsD)

Discord channel: PTB
OS: Windows
Mod: Betterdiscord
Discord language: English

**Comment by Gibbu** [comment]
All my themes got a structure change meaning the `base.css` file doesn't exist anymore.

All you have to do is just change the end of the url from `base.css` to `dist/[ThemeName].css`.
Example with Frosted Glass:
![image](https://user-images.githubusercontent.com/20338746/127092446-488b393d-1eb1-43f1-b75c-3d07aad2044f.png)

**Comment by Jan-aka-q0** [comment]
Works like a charm, thanks!
