### ISSUE TITLE
Spotify Rich Presence in user modal

### ISSUE THREAD

**Issue by EconomicSacks** [DiscordStyles/Slate#58]
**Describe the bug**  
*When someone has a Spotify account connect and they are listening to music it shows as a status in the user modal. But with this theme I don't even know what is happening.*  

**To Reproduce**  
*Connect a Spotify Account
Play a song
Open your user modal*  

**Screenshots**  

![image](https://user-images.githubusercontent.com/81370480/128444524-5c8bb72e-12af-4eb6-9037-cc6db5fcb1a3.png)
  

**Infomation (please complete the following information):**  
Discord channel: *Stable*  
OS: *Windows 10*  
Mod: *BetterDiscord*  
Discord language: *US English*

**Comment by Gibbu** [comment]
Not quite sure why yours looks so wack
![image](https://user-images.githubusercontent.com/20338746/128507572-b64100e4-7450-4d7e-9f45-94b81730e094.png)

Do you have any other plugins/themes enabled?

**Comment by EconomicSacks** [comment]
I do have a lot of plugins and a couple of misc themes.
