### ISSUE TITLE
User Avatars in user poput

### ISSUE THREAD

**Issue by EconomicSacks** [DiscordStyles/Slate#61]
**Describe the bug**  
*In the lastest Slate version I have noticed that when you open the user modal the profile picture is square but the cutout is circle. The problem is that it extends too far down and covers up the username*  

**To Reproduce**  
*Enable the latest Slate
Click on a user modal
Look at profile picture*  

**Screenshots**  
*![image](https://user-images.githubusercontent.com/81370480/129060346-04e13820-3488-495c-9a9c-c90df6953a48.png)*  

**Infomation (please complete the following information):**  
Discord channel: *Stable*  
OS: *Windows 10*  
Mod: *BetterDiscord*  
Discord language: *US English*

**Comment by Gibbu** [comment]
You must have a outdated Slate version.
![image](https://user-images.githubusercontent.com/20338746/129204850-e065c0da-aad5-40ab-b5c3-55a810e936ea.png)

**Comment by EconomicSacks** [comment]
1. I am on v1.1

2. Oh yeah sorry my bad

**Comment by beyond9thousand** [comment]
@EconomicSacks you should probably close this issue
