### ISSUE TITLE
Settings modal for roles blocks/hides roles list

### ISSUE THREAD

**Issue by beyond9thousand** [DiscordStyles/Slate#63]
Opening the roles menu under server settings blocks off the roles list.
![image](https://user-images.githubusercontent.com/77363063/131100382-5a94e409-abf1-47f9-8c19-9cd6f053411b.png)
![image](https://user-images.githubusercontent.com/77363063/131100577-e403ee0b-0a96-4c66-94b7-75b2c6da3a65.png)
![image](https://user-images.githubusercontent.com/77363063/131100468-4b4e48b3-6789-45d2-9d1c-f7e267c4c5c7.png)

**Comment by Gibbu** [comment]
Pretty much fixed, there's still the "Manage Members" tab to do but I cannot be bothered with that at the moment.
Discord for some unknown reason uses two different components for the exact same thing.

![gif](https://user-images.githubusercontent.com/20338746/131236244-f9a0708e-28c7-4483-af87-672a710597e9.gif)

**Comment by beyond9thousand** [comment]
Thank you so much for the fix! And yes, its ok. I really don't mind the aesthetic bug, it was just this functionality block which you have fixed graciously.
![yoOBl1cKii](https://user-images.githubusercontent.com/77363063/131238177-131d1591-db90-4597-ac32-10d301619d3c.gif)

**Comment by Gibbu** [comment]
Huh, yours is still kinda broken. Mind sending me your `.theme.css` file?

**Comment by beyond9thousand** [comment]
Oh don't worry that's probably due to my slate modal theme plugin added on top of this. Now that you mention it, i was wondering if the modal view box you've set in your theme could be bigger by default? It's kind of the reason I've added this over your theme.
![tGTXR05J3C](https://user-images.githubusercontent.com/77363063/131241561-872735a2-fdc1-4c67-8668-ddc83f7c4dd2.gif)

**Comment by Gibbu** [comment]
Ahhhh okay.

**Comment by Gibbu** [comment]
Here they are: https://github.com/DiscordStyles/Slate/wiki/Hidden-Variables#settings-modal-variables
```
--settings-min-height: 450px;
--settings-max-height: 650px;
--settings-min-width: 960px;
--settings-max-width: 960px;
```

**Comment by beyond9thousand** [comment]
Thanks! That fixes my minor scuffle as well
