### ISSUE TITLE
Large Gaps Between Messages Sent in a Short Amount of Time

### ISSUE THREAD

**Issue by UrkiMimi** [DiscordStyles/Slate#65]
**Describe the bug**  
*The bug makes it so there is large gaps when a user sends more than one message in a short amount of time.*  

**To Reproduce**  
*Send Multiple Messages*  

**Screenshots**  
*
![image](https://user-images.githubusercontent.com/74517821/134095989-a05cdbeb-0654-4abb-a171-c1689de2d382.png)
*  

**Infomation (please complete the following information):**  
Discord channel: *Canary*  
OS: *Windows*  
Mod: *Powercord*  
Discord language: *US English*  

**Additional context**  
*I booted up Discord this evening to find this bug*

**Comment by Gibbu** [comment]
Yep, and there's nothing I can do about it for now.
Discord has just change how the messages are rendered meaning it's not possible to detected which messages are start of a message group or not.

**Comment by Gibbu** [comment]
Fixed.

**Comment by UrkiMimi** [comment]
Thank you so much for this fix

**Comment by UrkiMimi** [comment]
![image](https://user-images.githubusercontent.com/74517821/145314397-8942746b-a166-4474-8787-bcbb54f2adb7.png)
