### ISSUE TITLE
New Message bar/Date marker overlaps blocked messages

### ISSUE THREAD

**Issue by NickHam13** [DiscordStyles/Slate#67]
**Describe the bug**  
Title. The spacing is also a bit weird even with normal messages. It looks fine when between two different message groups though.

**Screenshots**  
![image](https://user-images.githubusercontent.com/49380508/136681788-457b9181-7e2d-438e-8a7e-d33c6f529060.png)
![image](https://user-images.githubusercontent.com/49380508/136738491-eb5907cb-2872-483d-b7d7-20330b5b5df4.png)

**Infomation (please complete the following information):**  
Discord channel: Canary
OS: Windows
Mod: Powercord
Discord language: English

**Comment by Gibbu** [comment]
Doesn't seem to be an issue anymore?
