### ISSUE TITLE
top control bar clips into channel name when in a call

### ISSUE THREAD

**Issue by froginabowtie** [DiscordStyles/Slate#7]
![image](https://user-images.githubusercontent.com/68382132/94843180-3d588300-0414-11eb-87a3-2a8652ee2607.png)
when in a dms call, the top discord bar controls cut into the title of whichever dm/group you are in.
my screen resolution is 1366 x 768, i am using the latest version of slate, discord, and betterdiscord. this has been an issue since the update where we had to reinstall the theme from the betterdiscordlibary. if any more information is needed, just shoot me a message on discord - 「ディラン」 ✿#0001

**Comment by Gibbu** [comment]
Not even sure this is in Slate anymore as it caused too many issues.
