### ISSUE TITLE
Can't see typing indicator when emoji/gif/sticker menu is open

### ISSUE THREAD

**Issue by NickHam13** [DiscordStyles/Slate#71]
**Describe the bug**  
Since the typing indicator is in the bottom right corner of the chat area, you can't see it when the emoji/gif/sticker menu is open.

**Infomation (please complete the following information):**  
Discord channel: Canary
OS: Windows
Mod: Powercord
Discord language: English

**Comment by Gibbu** [comment]
Nothing I can do about this.
