### ISSUE TITLE
Messages posted right after mentions by the same author are displayed incorrectly

### ISSUE THREAD

**Issue by Thedoczek** [DiscordStyles/Slate#75]
How it looks like:
![image](https://user-images.githubusercontent.com/69758777/137687503-2419ff47-c59e-4fa4-afd9-47a4b5a2aa74.png)
![image](https://user-images.githubusercontent.com/69758777/137687510-821c0720-7cbb-4dc2-b868-e4bd5a3f87e4.png)

How it should look (normal spacing):
![image](https://user-images.githubusercontent.com/69758777/137687540-31c6c4a6-6156-4109-ab1e-9ae350735a75.png)

Windows 10 Stable BetterDiscord

**Comment by Gibbu** [comment]
Closing since there's no solution that I can think of.
