### ISSUE TITLE
Wrong sidebar margin on Canary 102204 (69da889)

### ISSUE THREAD

**Issue by mochaaP** [DiscordStyles/Slate#77]
**Describe the bug**
Sidebar is misaligned and folders are not properly themed.

**To Reproduce**
Apply this theme to DiscordCanary 102204 (69da889)

**Screenshots**
![image](https://user-images.githubusercontent.com/21154023/138506006-63978d93-7772-4e1e-83b6-b70f717c25f4.png)

**Infomation (please complete the following information):**
Discord channel: *Canary*
OS: *Linux*
Mod: *Powercord*
Discord language: *en_US*

**Additional context**

seealso: `.listItem-2Ig28I`

**Comment by UrkiMimi** [comment]
I will add more to this now. It seems like this issue carried over to the regular Discord app as well. I had this happen when I was using stylus for my mac that cannot run Discord for some reason.

**Comment by Gibbu** [comment]
This should be fixed.

Do the following:
1. Re-enable the theme.
2. Restart your Discord.
3. Disable Cache.
    \> Press `CTRL` + `SHIFT` + `i`.
    \> Go to the "Network" tab.
    \> Check "Disable Cache".
    \> Reload Discord.
    \> Repeat steps, uncheck "Disable Chache".
