### ISSUE TITLE
Chat is lowered

### ISSUE THREAD

**Issue by ErebusAres** [DiscordStyles/Slate#8]
![image](https://user-images.githubusercontent.com/3603760/95354662-4a4cfa80-088a-11eb-8838-c36cce478137.png)
Chat looks weird, looked fine yesterday.

edit: 
downloaded new file, just to verify, and it still looks the same as above.

**Comment by Tropix126** [comment]
Id recommend switching to cozy mode for the time being. I know this isn't a great solution as of right now, but I should get to it soon.

**Comment by Gibbu** [comment]
Fixed
