### ISSUE TITLE
Some visual bugs I found

### ISSUE THREAD

**Issue by MrDinosaur666** [DiscordStyles/Slate#84]
**Describe the bug**  
1. GIF/Stickers/Emoji buttons overlap the search bar 
![Screen Shot 2022-01-12 at 7 29 48 PM](https://user-images.githubusercontent.com/78523157/149520774-f27622e9-e5e2-47e7-bb04-5824d3e822b0.png)

2. Threads menu when hovering over a channel is default theme
![Screen Shot 2022-01-12 at 7 30 11 PM](https://user-images.githubusercontent.com/78523157/149520880-9fb8e058-465f-42db-ab82-7b721d34b5de.png)

3. When uploading a file, the blue outline around the text box is shifted too far down
![Screen Shot 2022-01-12 at 7 30 58 PM](https://user-images.githubusercontent.com/78523157/149520964-3c7cd37e-e6bb-4d2e-bd31-6eae670f8685.png)

4. "Jump" button in the Pinned section of channels is hidden below video posts (does not occur with text/image posts)
![Screen Shot 2022-01-12 at 7 35 32 PM](https://user-images.githubusercontent.com/78523157/149521053-f4c3763f-d6b5-4a2b-9ac0-ca022611eea9.png)

**To Reproduce**  
Install the Slate theme on any client mod and look at the areas I highlighted above

**Infomation:**  
Discord channel: *Tested on both Stable and Canary*  
OS: *OSX*  
Mod: *Tested on Powercord, BetterDiscord, and GooseMod*  
Discord language: *English*

**Comment by Gibbu** [comment]
Fixed all.

**Comment by MrDinosaur666** [comment]
Thanks for fixing it so quickly! Btw, how do you decrease the width of the members/channel lists?

**Comment by Gibbu** [comment]
https://github.com/DiscordStyles/Slate/wiki/Hidden-Variables#sidebars
