### ISSUE TITLE
Compatibility: Horizontal Server List

### ISSUE THREAD

**Issue by Hsinto** [DiscordStyles/Slate#88]
Vertical server list server name arrow appears on horizontal server list labels 

**To Reproduce**  
Turn on Horizontal Server List, hover over a server

**Screenshots**  
![image](https://user-images.githubusercontent.com/69600719/166551976-d719789e-f28f-4155-885f-12f4a048798e.png)

**Infomation (please complete the following information):**  
Discord channel: PTB
OS: Windows
Mod: BetterDiscord
Discord language: English

**Comment by Gibbu** [comment]
This was an issue with Horizontal Server List which has been fixed.
