### ISSUE TITLE
PSN connections logo does not display on a users profile.

### ISSUE THREAD

**Issue by Xanthus58** [DiscordStyles/Slate#92]
### Describe the bug
PSN connection logo doesn't display on users profile

### To Reproduce  
Find someone with a PSN connection and view their profile.

### Screenshots
![image](https://user-images.githubusercontent.com/66909997/174725643-248775cd-b15f-4ec9-938b-bcd6dae20a12.png)
![image](https://user-images.githubusercontent.com/66909997/174725681-f15aacdb-9e90-4121-847c-984b39d579f1.png)

### Infomation
**Discord channel**: *Canary*
**OS**: *Windows*  
**Mod**: *Powercord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Fixed.
