### ISSUE TITLE
Listen along logo is misaligned

### ISSUE THREAD

**Issue by Xanthus58** [DiscordStyles/Slate#93]
### Describe the bug
The listen along button across all instances I can find is misaligned 

### To Reproduce  
Have a user listen to a song on Spotify and view the listen along button.

### Screenshots
![image](https://user-images.githubusercontent.com/66909997/174728760-ecd91273-8245-47d6-a48d-2b586e4df55c.png)
![image](https://user-images.githubusercontent.com/66909997/174728846-9f3d33d7-482f-4e39-86dc-fe02ccb6c4c7.png)

### Infomation (please complete the following information)
**Discord channel**: *Canary*  
**OS**: *Windows*  
**Mod**: *Powercord*  
**Discord language**: *English*  

### Additional context
It is possible that for the popout menu it is my plugins; but testing with disabled plugins still return with the misaligned logo.

**Comment by Gibbu** [comment]
Fixed.
