### ISSUE TITLE
(possibly intended) Colors for speaking users are inconsistent

### ISSUE THREAD

**Issue by Xanthus58** [DiscordStyles/Slate#94]
### Describe the bug
Colours for speaking users is not consistent as long as a user is speaking in a discord server voice channel.

### To Reproduce  
> Join a discord call via a server
> Speak in the server
> Observe the mismatched colours (green and blue)

### Screenshots
![image](https://user-images.githubusercontent.com/66909997/174729248-703bf036-51fb-40d5-bb25-43680ac948a5.png)### 

**Discord channel**: *Canary*  
**OS**: *Windows*  
**Mod**: *Powercord*  
**Discord language**: *English*  

### Additional context
I'm unaware of if this is intentional but I thought I would bring it to your attention just in case.

**Comment by Gibbu** [comment]
Fixed.
