### ISSUE TITLE
Profile pictures aren't squares in dm calls

### ISSUE THREAD

**Issue by Xanthus58** [DiscordStyles/Slate#95]
### Describe the bug
Profile pictures are not aquare, and thusly do not align with the speaking border.
the coloration issue also persists from issue https://github.com/DiscordStyles/Slate/issues/94

### To Reproduce  
> Join a DM call with a user
> Speak and observe the issue

### Screens
![174731210-32e5ac38-b14e-4f17-9471-5146e95043a1](https://user-images.githubusercontent.com/66909997/174732080-e78e995b-3d75-4920-bda2-7c9697b219bf.png)
hots
![image](https://user-images.githubusercontent.com/66909997/174731210-32e5ac38-b14e-4f17-9471-5146e95043a1.png)

### Infomation (please complete the following information)
**Discord channel**: *Canary*  
**OS**: *Windows*  
**Mod**: *Powercord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Fixed.
