### ISSUE TITLE
Emoji icon is misaligned in the status section

### ISSUE THREAD

**Issue by Xanthus58** [DiscordStyles/Slate#96]
### Describe the bug
Emoji icon is misaligned in the status section

### To Reproduce  
> Open the status creator
> Observe the bug

### Screenshots
![image](https://user-images.githubusercontent.com/66909997/174793262-973b1f94-9c57-4338-a4b6-8a81b071b909.png)

### Infomation (please complete the following information)
**Discord channel**: *Canary*  
**OS**: *Windows*  
**Mod**: *Powercord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Fixed.
